Peer Review
BolajiOlajide/SpaceAllocator pull request #2
Opened 2017-02-15 19:45 UTC by andela-bolajide

# Get Peer Review for my Dojo Space Allocator

## What does this PR do?
- #### It serves as my first output in checkpoint 1

## Description of Task to be completed?

-   #### I have a working prototype of Dojo Space Allocator

## How should this be manually tested?

-  #### Instructions have been inlcuded in my README file.

2017-02-17 12:21 UTC, andela-mkamau commented on tests/test_fellow.py
> +		self.assertIsInstance(self.fellow,Fellow)
I see you are testing if `self.fellow` is an instance of `Fellow` class. Is this really necessary?

2017-02-17 12:29 UTC, andela-mkamau commented on tests/test_fellow.py
> +		self.assertEqual(first_char,'F')
Am curious as to why you are only checking if the first character of the `id` is an `F`. Why not create a couple of Fellow objects and check whether their ids are not identical? What do you think about that?

2017-02-17 12:30 UTC, andela-mkamau commented on tests/test_fellow.py
> +	unittest.main()
I like that you have kept your test simple and with singular concerns.

Could think of more tests for this Fellow class? More edge cases?

2017-02-17 12:31 UTC, andela-mkamau commented on tests/test_livingspace.py
> +		self.assertIsInstance(self.livingspace,LivingSpace)
Again, I am of the opinion that this test is unnecessary.

2017-02-17 12:34 UTC, andela-mkamau commented on tests/test_livingspace.py
> +		self.assertEqual(self.livingspace.max_no_occupants,4)
This method's docstring says that the maximum number of occupants allowed is 6 yet you are testing that the maximum number set is 4. Please review that.

2017-02-17 12:34 UTC, andela-mkamau commented on tests/test_livingspace.py
> +	unittest.main()
Think of more tests for this class including edge cases.

2017-02-17 12:36 UTC, andela-mkamau commented on tests/test_models.py
> +	unittest.main()
Again, I think these tests are not really needed.

2017-02-17 12:40 UTC, andela-mkamau commented on tests/test_staff.py
> +		self.assertEqual(first_char,'S')
Please review this method's  docstring. 
You could create a number of Staff objects and compare their `staff_id`s. I think that would make this test more conclusive.

2017-02-17 13:03 UTC, andela-mkamau reviewed
## General Comments
I am really impressed with the direction you are taking your project.

I have mostly looked at your tests. 
I see that you have began adding functionalities, especially within the Dojo class. In TDD fashion, you should ideally have written accompanying tests for those functionalities. 

- Update your .gitignore file to ignore pyc files
- Think of more tests cases. This is particularly important for the Dojo class where a lot i expected to take place.
- Try to make you commits smaller and more focussed. Have a look at [these recommendations](https://chris.beams.io/posts/git-commit/).
- Also checkout PEP8 guidelines

2017-02-17 13:56 UTC, andela-bolajide commented on tests/test_fellow.py
> +		self.assertIsInstance(self.fellow,Fellow)
I have corrected this.
You're right. Since i am already testing for the type there is no need to test the instance.

2017-02-17 14:03 UTC, andela-bolajide commented on tests/test_fellow.py
> +		self.assertEqual(first_char,'F')
Good point.
I've added a test to check if two different fellows have identical fellow id.

2017-02-17 14:10 UTC, andela-bolajide commented on tests/test_livingspace.py
> +		self.assertIsInstance(self.livingspace,LivingSpace)
I've corrected this.

2017-02-17 14:13 UTC, andela-bolajide commented on tests/test_livingspace.py
> +		self.assertEqual(self.livingspace.max_no_occupants,4)
Corrected!

2017-02-17 14:13 UTC, andela-bolajide commented on tests/test_models.py
> +	unittest.main()
Okay. I've removed them.

2017-02-17 14:27 UTC, andela-bolajide commented on tests/test_staff.py
> +		self.assertEqual(first_char,'S')
Done.

2017-02-20 13:09 UTC, hassan02 requested changes

2017-02-20 13:09 UTC, hassan02 commented on models/dojo.py
>                  Dojo.staff[self.full_name] = {}
A better way to do this is to save the staff or fellow details in form of an object and not a dictionary. e.g `Dojo.staff[new_staff.full_name] = new_staff` or `Dojo.staff[new_staff.id] = new_staff`. With this, you wouldn't need lines 83-86 and line 101-104.

2017-02-20 13:09 UTC, hassan02 commented on models/dojo.py
> +    def allocate_room(self,arg):
You seem to be instantiating Dojo multiple times. That is bad practice. A better way to do this is to create a single instance with `dojo = Dojo()` and use `dojo` in place of `Dojo()`

2017-02-21 17:27 UTC, mfalade commented on main.py
>  from models.dojo import Dojo
NIT: You should have a space between your inbuilt libraries, 3rd party libraries and project specific libraries import. 
Also, you should import in alphabetical order 

(that if you give a rat's ass about [PEP8 Standards](https://www.python.org/dev/peps/pep-0008/))

But seriously, this is recommended

2017-02-21 17:38 UTC, mfalade commented on main.py
> +                Dojo().allocate_room(arg)
`Dojo().allocate_room` ???

Everytime you do `Dojo()`, you create a new instance of the class. 

You shouldn't do this.
It's bad design.

Create one instance instead 

```python
the_only_dojo_you_need = Dojo()
...
the_only_dojo_you_need.allocate_room(arg)
```

If you MUST access the instance method this way (i.e using the `Dojo().do_something format`), then you should implement the Dojo class using the singleton pattern 
(I challenge you to try this on the side just for fun 💪 )

2017-02-21 17:39 UTC, mfalade commented on main.py
> +            print("")
Why print an empty string to the console ?

2017-02-22 22:50 UTC, andela-bolajide commented on main.py
> +            print("")
It's a method i was using to test. 
I've removed that empty and also the "else" condition as it serves no purpose here.

2017-02-22 22:56 UTC, andela-bolajide commented on tests/test_office.py
> +	def test_room_name(self):
Corrected that. 
I will make sure i pay attention to these tiny details.

2017-02-22 22:56 UTC, andela-bolajide commented on models/dojo.py
>      def __init__(self):
I agree with you.
I've removed it.

2017-02-22 22:58 UTC, andela-bolajide commented on models/dojo.py
>              if self.full_name not in Dojo.staff:
I'm using the full name of the person as a key to store data in the dictionary.

2017-02-23 05:02 UTC, andela-bolajide commented on models/dojo.py
> +    def allocate_room(self,arg):
Awesome.
Done that.

2017-02-23 05:03 UTC, andela-bolajide commented on models/dojo.py
>                  Dojo.staff[self.full_name] = {}
Done

2017-02-23 05:03 UTC, andela-bolajide commented on main.py
>  from models.dojo import Dojo
I've rearranged my import statements

2017-02-23 09:45 UTC, mfalade commented on models/fellow.py
> +		id = 'F' + ''.join(random.choice(string.ascii_uppercase + string.digits) for _ in range(7))
`id` is a built in Python keyword and shouldn't be used as a variable name.

`fellow_id` is a more suitable name.

2017-02-23 10:09 UTC, mfalade commented on models/fellow.py
> +		while id in self.fellow_data:
I'd suggest you you use `recursion` here instead.

You could decorate `get_fellow_id` as a class method, the have something like this

```python
@classmethod
def get_fellow_id(cls):
    fellow_id = 'F' + ''.join(random.choice(string.ascii_uppercase + string.digits) for _ in range(7))
    if fellow_id in cls.fellow_data:
        cls.get_fellow_id()
    return fellow_id

```

2017-02-23 12:33 UTC, andela-bolajide commented on models/fellow.py
> +		id = 'F' + ''.join(random.choice(string.ascii_uppercase + string.digits) for _ in range(7))
I've corrected that.

2017-02-23 14:41 UTC, andela-bolajide commented on main.py
> +                Dojo().allocate_room(arg)
Done. 
I have implemented the singleton pattern for instantiating my class.
Thanks.

2017-02-23 18:42 UTC, andela-bolajide commented on models/fellow.py
> +		while id in self.fellow_data:
Done!

2017-03-03 08:18 UTC, tsolarin commented on data/data_manager.py
> +                '''CREATE TABLE IF NOT EXISTS office (room_name PRIMARY KEY,room_type,occupants,current_number,max_no_occupants)''')
This SQL query is better as a variable, maybe a constant at the top?

2017-03-03 08:26 UTC, tsolarin commented on data/data_manager.py
> +            pass
No need for the `else` block here.

2017-03-03 08:33 UTC, tsolarin commented on models/staff.py
> +        while staff_id in Staff.staff_data:
Why not `self.staff_data`?

2017-03-03 08:44 UTC, tsolarin commented
@andela-bolajide you should purge this repo of `.pyc` files

2017-03-05 18:16 UTC, andela-bolajide commented on data/data_manager.py
> +            pass
I've removed it.

2017-03-05 18:24 UTC, andela-bolajide commented on models/staff.py
> +        while staff_id in Staff.staff_data:
Because i declared outside the __init__ statement but since it is also a class variable, i'll use self.staff_data.
Thanks

2017-03-08 13:48 UTC, njirap commented
How to write git commits `https://chris.beams.io/posts/git-commit/`

2017-03-08 13:52 UTC, njirap commented on .gitignore
> +models/*.pyc
isn't this already covered by L4

2017-03-08 14:01 UTC, njirap commented on main.py
> +            Dojo().allocate_room(arg)
this looks funny..

2017-03-08 14:05 UTC, njirap commented on main.py
> +        Dojo().purge(arg)
maybe only purge when the `arg` is a `yes` instead of checking for the yes in the "backend"

2017-03-08 14:10 UTC, njirap commented on models/fellow.py
> +        self.office_allocated = False
this can be gotten from `bool(self.office)`

2017-03-08 14:16 UTC, njirap commented on models/fellow.py
> +        return fellow_id
maybe append the new id to the `fellow_data` before you return it

2017-03-08 14:18 UTC, njirap commented on models/fellow.py
> +        if fellow_id in cls.fellow_data:
maybe a better variable name than `fellow_data` to better represent what that variable is about..

2017-03-08 14:19 UTC, njirap commented on models/livingspace.py
> +    """This creates a LivingSpace class which inherits from the Room Class."""
"""
Documentation goes here
"""

2017-03-08 14:27 UTC, njirap commented on models/staff.py
> +                ''.join(random.choice(string.ascii_uppercase + string.digits)
Practice being `DRY` in your code

2017-03-08 14:28 UTC, njirap commented on test_input3.txt
> +BOLAJI OLAJIDE STAFF
Maybe we just need 1 test_input files..

2017-03-08 14:30 UTC, njirap commented on tests/test_fellow.py
> +        self.assertEqual(type(self.fellow), Fellow)
under what circumstances would you instantiate `Fellow` and that instance not be an instance of `Fellow`?

2017-03-08 16:57 UTC, andela-bolajide commented on .gitignore
> +models/*.pyc
I have removed all duplicates.

2017-03-08 17:13 UTC, andela-bolajide commented on main.py
> +            Dojo().allocate_room(arg)
Hello @njirap,
When i changed to `Dojo.allocate_room(arg)` i get an error:

![screen shot 2017-03-08 at 5 59 26 pm](https://cloud.githubusercontent.com/assets/25608335/23714682/6e6d1868-042a-11e7-875e-a90186f72467.png)

Is it better if i probably allocate the instance of Dojo() to a variable? Something like:

`
self.dojo = Dojo()
self.dojo.allocate_room(arg)
`

2017-03-08 18:01 UTC, andela-bolajide commented on main.py
> +        Dojo().purge(arg)
Done.

2017-03-08 18:28 UTC, andela-bolajide commented on models/fellow.py
> +        self.office_allocated = False
Done.

2017-03-08 18:40 UTC, andela-bolajide commented on models/fellow.py
> +        return fellow_id
Done.

2017-03-08 18:40 UTC, andela-bolajide commented on models/fellow.py
> +        if fellow_id in cls.fellow_data:
Done.

2017-03-08 18:51 UTC, andela-bolajide commented on models/staff.py
> +                ''.join(random.choice(string.ascii_uppercase + string.digits)
Done.

2017-03-08 19:03 UTC, andela-bolajide commented on tests/test_fellow.py
> +        self.assertEqual(type(self.fellow), Fellow)
I have tested if the Fellow class is inheriting from the Person class.

2017-03-15 19:19 UTC, merged